apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "show-secrets-service.fullname" . }}
  labels:
    {{- include "show-secrets-service.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "show-secrets-service.fullname" . }}
  namespace: default
  labels:
    {{- include "show-secrets-service.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: default
roleRef:
  kind: Role
  name: {{ include "show-secrets-service.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
